### ISSUE TITLE
onscroll 方法失效

### ISSUE THREAD

**Issue by xiezhengyun** [duyanpeng/vue-quick-loadmore#1]
你好：
       我在使用过程中发现两个问题：
       1.容器 quick-loadmore 的onscroll无效。我的使用场景是，在手机页面滑动的时候，判断视频是否在可视窗口内，控制视频的暂停。
       2.点击视频播放的时候，即使暂停了，在上下滑动的时候，安卓机video元素，上下抖动严重。

**Comment by duyanpeng** [comment]
1.onscroll是在内部监听的用于处理无限滚动，在外部监听是监听不到的。你可以把我的源代码粘到项目里src/vueQuickmore.vue,在里面加上onscroll的回调。
2.视频这方面我没有做过，你可以试一下better-scroll等滚动库，因为我的不是基于translate做的滚动
