### ISSUE TITLE
top-method触发条件异常！

### ISSUE THREAD

**Issue by xwlaix** [duyanpeng/vue-quick-loadmore#2]
内容加载比较多，返回到顶部之后，只执行点击，就会触发上拉刷新动作。

**Comment by duyanpeng** [comment]
我个人测试这里没问题。
另外，是ios和安卓都有这个问题还是个别系统个别浏览器有问题？
内容比较多是多多？
建议，复制我的例子单独跑一下，我设置的参数不要动，数据量和你的一样多看有没有相同的问题。

**Comment by xwlaix** [comment]
最小demo应该是没问题的，我这边的是放在一个element table中，在跨越大概一个屏幕，返回顶部之后点击出现刷新，应该是哪里判断存在问题，我这边先禁止上拉刷新了。

**Comment by duyanpeng** [comment]
我组件写在一个.vue文件里了，你可以去我src里把组件直接粘贴到你项目里调试，看看是不是我组件的问题，有问题可以直接改，npm 安装的你调试比较困难。
