### ISSUE TITLE
garen-loadmore插件在低版本ios系统中会导致白屏

### ISSUE THREAD

**Issue by jiulanrensan** [duyanpeng/vue-quick-loadmore#3]
部分IOS12的iPhone 6，  IOS10.x 的iPhone6s在打开页面时就出现了白屏，并且报错：
![异常](https://user-images.githubusercontent.com/30172955/59906844-43ec0280-943c-11e9-8194-99039c02a02c.png)
改回vue-quick-loadmore之后就没有这个问题出现了，请问这是什么原因呢？

**Comment by duyanpeng** [comment]
我搜了一下dist之后的代码，应该是有一个const，webpack没给编译成var,我更新一下

**Comment by duyanpeng** [comment]
已更新修复问题
