### ISSUE TITLE
这样使用时为何会更改我页面的参数？？

### ISSUE THREAD

**Issue by owen-gxz** [duyanpeng/vue-quick-loadmore#4]
![image](https://user-images.githubusercontent.com/8510542/62696156-6a74f580-ba0a-11e9-98f2-4ee66e7bad43.png)

**Comment by duyanpeng** [comment]
没看懂，什么页面参数，路由参数吗？
另外截图代码有点少，看一下文档，提供了获取滚动距离和设置滚动距离的api。

**Comment by owen-gxz** [comment]
就是我的一个scroll字段是一个bool。。把我截图这一段注释了就不会有问题。。

**Comment by owen-gxz** [comment]
```
var _this = this
        setInterval(function () {
          if (!_this.scroll) {
            return
          }
          var container = _this.$el.querySelector(".content");
          container.scrollTop = container.scrollHeight;
        }, 100)
```

**Comment by owen-gxz** [comment]
这样的一段。竟然他会主动的更改我的scroll

**Comment by duyanpeng** [comment]
还是不知道你的需求是什么，我的scroll事件是在组件内部监听的，暴露了三个方法，一个是获得滚动距离，一个是设置滚动距离，一个是scroll事件，你这样直接设置scrollTop会和我内部冲突，我内部也使用了这个方法，最好不要这么写，你可以说一下你的需求，我看看怎么实现好。

**Comment by owen-gxz** [comment]
我应该知道那里的问题了
